server:
  port: 8001

spring:
  application:
    name: wangjun-blog
  datasource:
    username: root    # ????????
    password: 123456  # ???????
    # ??????????mysql8?
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
